export default   [
  {
    id: 1,
    title: 'Colors',
    description: 'Choose from three bold finishes. iPhone 17 Pro shown in Cosmic Orange.',
    isActive: false,
    img: "orange.jpg",
  },
  {
    id: 2,
    title: 'Aluminum unibody.',
    description: 'Optimized for performance and battery. Aluminum alloy is remarkably light and has exceptional thermal conductivity.',
    isActive: false,
    img: "unibody.jpg",
    content: {
      type: 'video',
      url: 'unibody.mp4',
      cover: "unibody.jpg",
    },
  },
  {
    id: 3,
    title: 'Vapor chamber.',
    description: 'Deionized water sealed inside moves heat away from the A19 Pro chip, allowing for even higher sustained performance.',
    isActive: false,
    content: {
      type: 'video',
      url: 'vapor.mp4',
      cover: "vapor.jpg",
    },
  },
  {
    id: 4,
    title: 'Ceramic Shield.',
    description: 'Protects the back of iPhone 17 Pro, making it 4x more resistant to cracks.4 New Ceramic Shield 2 on the front has 3x better scratch resistance.',
    isActive: false,
    img: "ceramic.jpg",
  },
  {
    id: 5,
    title: 'Immersive pro display.',
    description: 'Our best‑ever 6.3‑inch and 6.9‑inch Super Retina XDR displays.6 Brighter. Better anti‑reflection. ProMotion up to 120Hz.',
    isActive: false,
    img: "display.jpg",
  },
  {
    id: 6,
    title: 'Camera Control.',
    description: 'Instantly take a photo, record video, adjust settings, and more. So you never miss a moment.',
    isActive: false,
    img: "camera.jpg",
  },
  {
    id: 7,
    title: 'Action button.',
    description: 'A customizable fast track to your favorite feature. Long press to launch the action you want — Silent mode, Translation, Shortcuts, and more.',
    isActive: false,
    img: "action.jpg",
  },
]