import type { Metadata } from "next";
import "./globals.css";
import Navbar from '@/components/Navbar';
import SideBar from '@/components/SideBar';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <SideBar />
        <Navbar />
        {children}
      </body>
    </html>
  );
}
