// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: recommendation.proto

// КиноСоветник — gRPC-контракт сервиса рекомендаций.
// Общий контракт API (NestJS) и recommendation-service (Go): proto-loader
// на стороне Node читает этот файл в рантайме, Go-сторона использует
// сгенерированный код (scripts/protogen.sh -> internal/pb).

package cinepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Кандидат афиши — фильм, который вообще можно забронировать.
type MovieCandidate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MovieId       string                 `protobuf:"bytes,1,opt,name=movie_id,json=movieId,proto3" json:"movie_id,omitempty"` // uuid фильма в БД API
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Genre         string                 `protobuf:"bytes,3,opt,name=genre,proto3" json:"genre,omitempty"`                            // жанр-строка афиши («фантастика»)
	RatingAvg     float64                `protobuf:"fixed64,4,opt,name=rating_avg,json=ratingAvg,proto3" json:"rating_avg,omitempty"` // средний рейтинг 0..5, 0 = отзывов нет
	RatingCount   int32                  `protobuf:"varint,5,opt,name=rating_count,json=ratingCount,proto3" json:"rating_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MovieCandidate) Reset() {
	*x = MovieCandidate{}
	mi := &file_recommendation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MovieCandidate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MovieCandidate) ProtoMessage() {}

func (x *MovieCandidate) ProtoReflect() protoreflect.Message {
	mi := &file_recommendation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MovieCandidate.ProtoReflect.Descriptor instead.
func (*MovieCandidate) Descriptor() ([]byte, []int) {
	return file_recommendation_proto_rawDescGZIP(), []int{0}
}

func (x *MovieCandidate) GetMovieId() string {
	if x != nil {
		return x.MovieId
	}
	return ""
}

func (x *MovieCandidate) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *MovieCandidate) GetGenre() string {
	if x != nil {
		return x.Genre
	}
	return ""
}

func (x *MovieCandidate) GetRatingAvg() float64 {
	if x != nil {
		return x.RatingAvg
	}
	return 0
}

func (x *MovieCandidate) GetRatingCount() int32 {
	if x != nil {
		return x.RatingCount
	}
	return 0
}

type RecommendationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // uuid зрителя
	Candidates    []*MovieCandidate      `protobuf:"bytes,2,rep,name=candidates,proto3" json:"candidates,omitempty"`       // афиша от API
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`                // топ-N; <=0 = дефолт 4
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecommendationsRequest) Reset() {
	*x = RecommendationsRequest{}
	mi := &file_recommendation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecommendationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecommendationsRequest) ProtoMessage() {}

func (x *RecommendationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_recommendation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecommendationsRequest.ProtoReflect.Descriptor instead.
func (*RecommendationsRequest) Descriptor() ([]byte, []int) {
	return file_recommendation_proto_rawDescGZIP(), []int{1}
}

func (x *RecommendationsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RecommendationsRequest) GetCandidates() []*MovieCandidate {
	if x != nil {
		return x.Candidates
	}
	return nil
}

func (x *RecommendationsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type RecommendationItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MovieId       string                 `protobuf:"bytes,1,opt,name=movie_id,json=movieId,proto3" json:"movie_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Genre         string                 `protobuf:"bytes,3,opt,name=genre,proto3" json:"genre,omitempty"`
	Score         float64                `protobuf:"fixed64,4,opt,name=score,proto3" json:"score,omitempty"` // 0..1 — нормализованный скор для витрины
	Reason        string                 `protobuf:"bytes,5,opt,name=reason,proto3" json:"reason,omitempty"` // причина на русском: «вы часто смотрите фантастику»
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecommendationItem) Reset() {
	*x = RecommendationItem{}
	mi := &file_recommendation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecommendationItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecommendationItem) ProtoMessage() {}

func (x *RecommendationItem) ProtoReflect() protoreflect.Message {
	mi := &file_recommendation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecommendationItem.ProtoReflect.Descriptor instead.
func (*RecommendationItem) Descriptor() ([]byte, []int) {
	return file_recommendation_proto_rawDescGZIP(), []int{2}
}

func (x *RecommendationItem) GetMovieId() string {
	if x != nil {
		return x.MovieId
	}
	return ""
}

func (x *RecommendationItem) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *RecommendationItem) GetGenre() string {
	if x != nil {
		return x.Genre
	}
	return ""
}

func (x *RecommendationItem) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *RecommendationItem) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type RecommendationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*RecommendationItem  `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Basis         string                 `protobuf:"bytes,2,opt,name=basis,proto3" json:"basis,omitempty"` // profile | popular | empty — на чём построен топ
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecommendationsResponse) Reset() {
	*x = RecommendationsResponse{}
	mi := &file_recommendation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecommendationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecommendationsResponse) ProtoMessage() {}

func (x *RecommendationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_recommendation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecommendationsResponse.ProtoReflect.Descriptor instead.
func (*RecommendationsResponse) Descriptor() ([]byte, []int) {
	return file_recommendation_proto_rawDescGZIP(), []int{3}
}

func (x *RecommendationsResponse) GetItems() []*RecommendationItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *RecommendationsResponse) GetBasis() string {
	if x != nil {
		return x.Basis
	}
	return ""
}

var File_recommendation_proto protoreflect.FileDescriptor

const file_recommendation_proto_rawDesc = "" +
	"\n" +
	"\x14recommendation.proto\x12\x17cine.recommendations.v1\"\x99\x01\n" +
	"\x0eMovieCandidate\x12\x19\n" +
	"\bmovie_id\x18\x01 \x01(\tR\amovieId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x14\n" +
	"\x05genre\x18\x03 \x01(\tR\x05genre\x12\x1d\n" +
	"\n" +
	"rating_avg\x18\x04 \x01(\x01R\tratingAvg\x12!\n" +
	"\frating_count\x18\x05 \x01(\x05R\vratingCount\"\x90\x01\n" +
	"\x16RecommendationsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12G\n" +
	"\n" +
	"candidates\x18\x02 \x03(\v2'.cine.recommendations.v1.MovieCandidateR\n" +
	"candidates\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"\x89\x01\n" +
	"\x12RecommendationItem\x12\x19\n" +
	"\bmovie_id\x18\x01 \x01(\tR\amovieId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x14\n" +
	"\x05genre\x18\x03 \x01(\tR\x05genre\x12\x14\n" +
	"\x05score\x18\x04 \x01(\x01R\x05score\x12\x16\n" +
	"\x06reason\x18\x05 \x01(\tR\x06reason\"r\n" +
	"\x17RecommendationsResponse\x12A\n" +
	"\x05items\x18\x01 \x03(\v2+.cine.recommendations.v1.RecommendationItemR\x05items\x12\x14\n" +
	"\x05basis\x18\x02 \x01(\tR\x05basis2\x8a\x01\n" +
	"\x0fRecommendations\x12w\n" +
	"\x12GetRecommendations\x12/.cine.recommendations.v1.RecommendationsRequest\x1a0.cine.recommendations.v1.RecommendationsResponseB+Z)recommendation-service/internal/pb;cinepbb\x06proto3"

var (
	file_recommendation_proto_rawDescOnce sync.Once
	file_recommendation_proto_rawDescData []byte
)

func file_recommendation_proto_rawDescGZIP() []byte {
	file_recommendation_proto_rawDescOnce.Do(func() {
		file_recommendation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_recommendation_proto_rawDesc), len(file_recommendation_proto_rawDesc)))
	})
	return file_recommendation_proto_rawDescData
}

var file_recommendation_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_recommendation_proto_goTypes = []any{
	(*MovieCandidate)(nil),          // 0: cine.recommendations.v1.MovieCandidate
	(*RecommendationsRequest)(nil),  // 1: cine.recommendations.v1.RecommendationsRequest
	(*RecommendationItem)(nil),      // 2: cine.recommendations.v1.RecommendationItem
	(*RecommendationsResponse)(nil), // 3: cine.recommendations.v1.RecommendationsResponse
}
var file_recommendation_proto_depIdxs = []int32{
	0, // 0: cine.recommendations.v1.RecommendationsRequest.candidates:type_name -> cine.recommendations.v1.MovieCandidate
	2, // 1: cine.recommendations.v1.RecommendationsResponse.items:type_name -> cine.recommendations.v1.RecommendationItem
	1, // 2: cine.recommendations.v1.Recommendations.GetRecommendations:input_type -> cine.recommendations.v1.RecommendationsRequest
	3, // 3: cine.recommendations.v1.Recommendations.GetRecommendations:output_type -> cine.recommendations.v1.RecommendationsResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_recommendation_proto_init() }
func file_recommendation_proto_init() {
	if File_recommendation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_recommendation_proto_rawDesc), len(file_recommendation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_recommendation_proto_goTypes,
		DependencyIndexes: file_recommendation_proto_depIdxs,
		MessageInfos:      file_recommendation_proto_msgTypes,
	}.Build()
	File_recommendation_proto = out.File
	file_recommendation_proto_goTypes = nil
	file_recommendation_proto_depIdxs = nil
}
