// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: recommendation.proto

// КиноСоветник — gRPC-контракт сервиса рекомендаций.
// Общий контракт API (NestJS) и recommendation-service (Go): proto-loader
// на стороне Node читает этот файл в рантайме, Go-сторона использует
// сгенерированный код (scripts/protogen.sh -> internal/pb).

package cinepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Recommendations_GetRecommendations_FullMethodName = "/cine.recommendations.v1.Recommendations/GetRecommendations"
)

// RecommendationsClient is the client API for Recommendations service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Сервис персональных рекомендаций. Профили зрителей строит сам из сигналов
// RabbitMQ (подтверждённые брони, отзывы); кандидатов ему передаёт API —
// текущая афиша, поэтому сервису не нужно хранить каталог фильмов.
type RecommendationsClient interface {
	// Топ фильмов для зрителя среди переданных кандидатов.
	GetRecommendations(ctx context.Context, in *RecommendationsRequest, opts ...grpc.CallOption) (*RecommendationsResponse, error)
}

type recommendationsClient struct {
	cc grpc.ClientConnInterface
}

func NewRecommendationsClient(cc grpc.ClientConnInterface) RecommendationsClient {
	return &recommendationsClient{cc}
}

func (c *recommendationsClient) GetRecommendations(ctx context.Context, in *RecommendationsRequest, opts ...grpc.CallOption) (*RecommendationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecommendationsResponse)
	err := c.cc.Invoke(ctx, Recommendations_GetRecommendations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RecommendationsServer is the server API for Recommendations service.
// All implementations must embed UnimplementedRecommendationsServer
// for forward compatibility.
//
// Сервис персональных рекомендаций. Профили зрителей строит сам из сигналов
// RabbitMQ (подтверждённые брони, отзывы); кандидатов ему передаёт API —
// текущая афиша, поэтому сервису не нужно хранить каталог фильмов.
type RecommendationsServer interface {
	// Топ фильмов для зрителя среди переданных кандидатов.
	GetRecommendations(context.Context, *RecommendationsRequest) (*RecommendationsResponse, error)
	mustEmbedUnimplementedRecommendationsServer()
}

// UnimplementedRecommendationsServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRecommendationsServer struct{}

func (UnimplementedRecommendationsServer) GetRecommendations(context.Context, *RecommendationsRequest) (*RecommendationsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRecommendations not implemented")
}
func (UnimplementedRecommendationsServer) mustEmbedUnimplementedRecommendationsServer() {}
func (UnimplementedRecommendationsServer) testEmbeddedByValue()                         {}

// UnsafeRecommendationsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RecommendationsServer will
// result in compilation errors.
type UnsafeRecommendationsServer interface {
	mustEmbedUnimplementedRecommendationsServer()
}

func RegisterRecommendationsServer(s grpc.ServiceRegistrar, srv RecommendationsServer) {
	// If the following call panics, it indicates UnimplementedRecommendationsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Recommendations_ServiceDesc, srv)
}

func _Recommendations_GetRecommendations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecommendationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecommendationsServer).GetRecommendations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Recommendations_GetRecommendations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecommendationsServer).GetRecommendations(ctx, req.(*RecommendationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Recommendations_ServiceDesc is the grpc.ServiceDesc for Recommendations service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Recommendations_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cine.recommendations.v1.Recommendations",
	HandlerType: (*RecommendationsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetRecommendations",
			Handler:    _Recommendations_GetRecommendations_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "recommendation.proto",
}
