// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: pricing.proto

// Pricing — gRPC-контракт «Тарификатора»: сервиса динамических цен.
// Общий контракт API (NestJS) и pricing-service (Go): proto-loader
// на стороне Node читает этот файл в рантайме, Go-сторона использует
// сгенерированный код (scripts/protogen.sh -> internal/pb).

package cinepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QuoteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`             // uuid сеанса — ключ проекции спроса
	SessionAt     string                 `protobuf:"bytes,2,opt,name=session_at,json=sessionAt,proto3" json:"session_at,omitempty"`             // момент сеанса, RFC3339 (правила времени)
	BasePriceRub  int32                  `protobuf:"varint,3,opt,name=base_price_rub,json=basePriceRub,proto3" json:"base_price_rub,omitempty"` // базовая цена фильма из афиши, ₽/место
	Capacity      int32                  `protobuf:"varint,4,opt,name=capacity,proto3" json:"capacity,omitempty"`                               // ёмкость зала (геометрия общая, 8×10)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuoteRequest) Reset() {
	*x = QuoteRequest{}
	mi := &file_pricing_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuoteRequest) ProtoMessage() {}

func (x *QuoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pricing_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuoteRequest.ProtoReflect.Descriptor instead.
func (*QuoteRequest) Descriptor() ([]byte, []int) {
	return file_pricing_proto_rawDescGZIP(), []int{0}
}

func (x *QuoteRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *QuoteRequest) GetSessionAt() string {
	if x != nil {
		return x.SessionAt
	}
	return ""
}

func (x *QuoteRequest) GetBasePriceRub() int32 {
	if x != nil {
		return x.BasePriceRub
	}
	return 0
}

func (x *QuoteRequest) GetCapacity() int32 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

// Фактор цены: слагаемое раскладки. Отсутствие фактора — множитель 1.
type PriceFactor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`        // morning | evening | weekend | demand_low | demand_high | demand_full
	Label         string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`      // человекочитаемо: «вечерний прайм +20%»
	Percent       int32                  `protobuf:"varint,3,opt,name=percent,proto3" json:"percent,omitempty"` // вклад фактора, %: −20 … +25
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PriceFactor) Reset() {
	*x = PriceFactor{}
	mi := &file_pricing_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PriceFactor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PriceFactor) ProtoMessage() {}

func (x *PriceFactor) ProtoReflect() protoreflect.Message {
	mi := &file_pricing_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PriceFactor.ProtoReflect.Descriptor instead.
func (*PriceFactor) Descriptor() ([]byte, []int) {
	return file_pricing_proto_rawDescGZIP(), []int{1}
}

func (x *PriceFactor) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *PriceFactor) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *PriceFactor) GetPercent() int32 {
	if x != nil {
		return x.Percent
	}
	return 0
}

type QuoteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PriceRub      int32                  `protobuf:"varint,1,opt,name=price_rub,json=priceRub,proto3" json:"price_rub,omitempty"`               // цена места после факторов, кратно 10 ₽
	BasePriceRub  int32                  `protobuf:"varint,2,opt,name=base_price_rub,json=basePriceRub,proto3" json:"base_price_rub,omitempty"` // базовая цена для сравнения
	Factors       []*PriceFactor         `protobuf:"bytes,3,rep,name=factors,proto3" json:"factors,omitempty"`                                  // применённые факторы (может быть пусто)
	Occupied      int32                  `protobuf:"varint,4,opt,name=occupied,proto3" json:"occupied,omitempty"`                               // занятые места проекции спроса
	Capacity      int32                  `protobuf:"varint,5,opt,name=capacity,proto3" json:"capacity,omitempty"`                               // ёмкость зала из запроса
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuoteResponse) Reset() {
	*x = QuoteResponse{}
	mi := &file_pricing_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuoteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuoteResponse) ProtoMessage() {}

func (x *QuoteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pricing_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuoteResponse.ProtoReflect.Descriptor instead.
func (*QuoteResponse) Descriptor() ([]byte, []int) {
	return file_pricing_proto_rawDescGZIP(), []int{2}
}

func (x *QuoteResponse) GetPriceRub() int32 {
	if x != nil {
		return x.PriceRub
	}
	return 0
}

func (x *QuoteResponse) GetBasePriceRub() int32 {
	if x != nil {
		return x.BasePriceRub
	}
	return 0
}

func (x *QuoteResponse) GetFactors() []*PriceFactor {
	if x != nil {
		return x.Factors
	}
	return nil
}

func (x *QuoteResponse) GetOccupied() int32 {
	if x != nil {
		return x.Occupied
	}
	return 0
}

func (x *QuoteResponse) GetCapacity() int32 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

var File_pricing_proto protoreflect.FileDescriptor

const file_pricing_proto_rawDesc = "" +
	"\n" +
	"\rpricing.proto\x12\x0fcine.pricing.v1\"\x8e\x01\n" +
	"\fQuoteRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1d\n" +
	"\n" +
	"session_at\x18\x02 \x01(\tR\tsessionAt\x12$\n" +
	"\x0ebase_price_rub\x18\x03 \x01(\x05R\fbasePriceRub\x12\x1a\n" +
	"\bcapacity\x18\x04 \x01(\x05R\bcapacity\"Q\n" +
	"\vPriceFactor\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x12\x18\n" +
	"\apercent\x18\x03 \x01(\x05R\apercent\"\xc2\x01\n" +
	"\rQuoteResponse\x12\x1b\n" +
	"\tprice_rub\x18\x01 \x01(\x05R\bpriceRub\x12$\n" +
	"\x0ebase_price_rub\x18\x02 \x01(\x05R\fbasePriceRub\x126\n" +
	"\afactors\x18\x03 \x03(\v2\x1c.cine.pricing.v1.PriceFactorR\afactors\x12\x1a\n" +
	"\boccupied\x18\x04 \x01(\x05R\boccupied\x12\x1a\n" +
	"\bcapacity\x18\x05 \x01(\x05R\bcapacity2Q\n" +
	"\aPricing\x12F\n" +
	"\x05Quote\x12\x1d.cine.pricing.v1.QuoteRequest\x1a\x1e.cine.pricing.v1.QuoteResponseB$Z\"pricing-service/internal/pb;cinepbb\x06proto3"

var (
	file_pricing_proto_rawDescOnce sync.Once
	file_pricing_proto_rawDescData []byte
)

func file_pricing_proto_rawDescGZIP() []byte {
	file_pricing_proto_rawDescOnce.Do(func() {
		file_pricing_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pricing_proto_rawDesc), len(file_pricing_proto_rawDesc)))
	})
	return file_pricing_proto_rawDescData
}

var file_pricing_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_pricing_proto_goTypes = []any{
	(*QuoteRequest)(nil),  // 0: cine.pricing.v1.QuoteRequest
	(*PriceFactor)(nil),   // 1: cine.pricing.v1.PriceFactor
	(*QuoteResponse)(nil), // 2: cine.pricing.v1.QuoteResponse
}
var file_pricing_proto_depIdxs = []int32{
	1, // 0: cine.pricing.v1.QuoteResponse.factors:type_name -> cine.pricing.v1.PriceFactor
	0, // 1: cine.pricing.v1.Pricing.Quote:input_type -> cine.pricing.v1.QuoteRequest
	2, // 2: cine.pricing.v1.Pricing.Quote:output_type -> cine.pricing.v1.QuoteResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pricing_proto_init() }
func file_pricing_proto_init() {
	if File_pricing_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pricing_proto_rawDesc), len(file_pricing_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pricing_proto_goTypes,
		DependencyIndexes: file_pricing_proto_depIdxs,
		MessageInfos:      file_pricing_proto_msgTypes,
	}.Build()
	File_pricing_proto = out.File
	file_pricing_proto_goTypes = nil
	file_pricing_proto_depIdxs = nil
}
