// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: pricing.proto

// Pricing — gRPC-контракт «Тарификатора»: сервиса динамических цен.
// Общий контракт API (NestJS) и pricing-service (Go): proto-loader
// на стороне Node читает этот файл в рантайме, Go-сторона использует
// сгенерированный код (scripts/protogen.sh -> internal/pb).

package cinepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Pricing_Quote_FullMethodName = "/cine.pricing.v1.Pricing/Quote"
)

// PricingClient is the client API for Pricing service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Сервис цен: API спрашивает цену места сеанса при создании брони
// и для витрины выбора. Спрос сервис копит сам — из событий брони
// в RabbitMQ (booking.payment.wait / waitlist.seat.released).
type PricingClient interface {
	// Цена одного места сеанса с раскладкой факторов. Состояние
	// вне запроса — только проекция спроса, ошибки гасятся
	// fallback'ом на базовую цену на стороне вызывающего.
	Quote(ctx context.Context, in *QuoteRequest, opts ...grpc.CallOption) (*QuoteResponse, error)
}

type pricingClient struct {
	cc grpc.ClientConnInterface
}

func NewPricingClient(cc grpc.ClientConnInterface) PricingClient {
	return &pricingClient{cc}
}

func (c *pricingClient) Quote(ctx context.Context, in *QuoteRequest, opts ...grpc.CallOption) (*QuoteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QuoteResponse)
	err := c.cc.Invoke(ctx, Pricing_Quote_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PricingServer is the server API for Pricing service.
// All implementations must embed UnimplementedPricingServer
// for forward compatibility.
//
// Сервис цен: API спрашивает цену места сеанса при создании брони
// и для витрины выбора. Спрос сервис копит сам — из событий брони
// в RabbitMQ (booking.payment.wait / waitlist.seat.released).
type PricingServer interface {
	// Цена одного места сеанса с раскладкой факторов. Состояние
	// вне запроса — только проекция спроса, ошибки гасятся
	// fallback'ом на базовую цену на стороне вызывающего.
	Quote(context.Context, *QuoteRequest) (*QuoteResponse, error)
	mustEmbedUnimplementedPricingServer()
}

// UnimplementedPricingServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPricingServer struct{}

func (UnimplementedPricingServer) Quote(context.Context, *QuoteRequest) (*QuoteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Quote not implemented")
}
func (UnimplementedPricingServer) mustEmbedUnimplementedPricingServer() {}
func (UnimplementedPricingServer) testEmbeddedByValue()                 {}

// UnsafePricingServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PricingServer will
// result in compilation errors.
type UnsafePricingServer interface {
	mustEmbedUnimplementedPricingServer()
}

func RegisterPricingServer(s grpc.ServiceRegistrar, srv PricingServer) {
	// If the following call panics, it indicates UnimplementedPricingServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Pricing_ServiceDesc, srv)
}

func _Pricing_Quote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PricingServer).Quote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Pricing_Quote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PricingServer).Quote(ctx, req.(*QuoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Pricing_ServiceDesc is the grpc.ServiceDesc for Pricing service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Pricing_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cine.pricing.v1.Pricing",
	HandlerType: (*PricingServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Quote",
			Handler:    _Pricing_Quote_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pricing.proto",
}
