// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: reminder.proto

// Reminder — gRPC-контракт сервиса напоминаний о сеансах.
// Общий контракт API (NestJS) и reminder-service (Go): proto-loader
// на стороне Node читает этот файл в рантайме, Go-сторона использует
// сгенерированный код (scripts/protogen.sh -> internal/pb).

package cinepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ScheduleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookingId     string                 `protobuf:"bytes,1,opt,name=booking_id,json=bookingId,proto3" json:"booking_id,omitempty"`    // uuid брони — ключ идемпотентности
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`             // uuid зрителя (владелец брони)
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`                             // адресат «письма»-напоминания
	MovieId       string                 `protobuf:"bytes,4,opt,name=movie_id,json=movieId,proto3" json:"movie_id,omitempty"`          // uuid фильма
	MovieTitle    string                 `protobuf:"bytes,5,opt,name=movie_title,json=movieTitle,proto3" json:"movie_title,omitempty"` // для текста письма и витрины
	Hall          string                 `protobuf:"bytes,6,opt,name=hall,proto3" json:"hall,omitempty"`                               // зал сеанса
	SessionAt     string                 `protobuf:"bytes,7,opt,name=session_at,json=sessionAt,proto3" json:"session_at,omitempty"`    // момент сеанса, RFC3339
	Seats         []string               `protobuf:"bytes,8,rep,name=seats,proto3" json:"seats,omitempty"`                             // места брони
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScheduleRequest) Reset() {
	*x = ScheduleRequest{}
	mi := &file_reminder_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScheduleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduleRequest) ProtoMessage() {}

func (x *ScheduleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reminder_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduleRequest.ProtoReflect.Descriptor instead.
func (*ScheduleRequest) Descriptor() ([]byte, []int) {
	return file_reminder_proto_rawDescGZIP(), []int{0}
}

func (x *ScheduleRequest) GetBookingId() string {
	if x != nil {
		return x.BookingId
	}
	return ""
}

func (x *ScheduleRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ScheduleRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *ScheduleRequest) GetMovieId() string {
	if x != nil {
		return x.MovieId
	}
	return ""
}

func (x *ScheduleRequest) GetMovieTitle() string {
	if x != nil {
		return x.MovieTitle
	}
	return ""
}

func (x *ScheduleRequest) GetHall() string {
	if x != nil {
		return x.Hall
	}
	return ""
}

func (x *ScheduleRequest) GetSessionAt() string {
	if x != nil {
		return x.SessionAt
	}
	return ""
}

func (x *ScheduleRequest) GetSeats() []string {
	if x != nil {
		return x.Seats
	}
	return nil
}

type ScheduleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`            // SCHEDULED
	DueAt         string                 `protobuf:"bytes,2,opt,name=due_at,json=dueAt,proto3" json:"due_at,omitempty"` // момент отправки письма (сеанс − окно), RFC3339
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScheduleResponse) Reset() {
	*x = ScheduleResponse{}
	mi := &file_reminder_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScheduleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduleResponse) ProtoMessage() {}

func (x *ScheduleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reminder_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduleResponse.ProtoReflect.Descriptor instead.
func (*ScheduleResponse) Descriptor() ([]byte, []int) {
	return file_reminder_proto_rawDescGZIP(), []int{1}
}

func (x *ScheduleResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ScheduleResponse) GetDueAt() string {
	if x != nil {
		return x.DueAt
	}
	return ""
}

type CancelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookingId     string                 `protobuf:"bytes,1,opt,name=booking_id,json=bookingId,proto3" json:"booking_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelRequest) Reset() {
	*x = CancelRequest{}
	mi := &file_reminder_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelRequest) ProtoMessage() {}

func (x *CancelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reminder_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelRequest.ProtoReflect.Descriptor instead.
func (*CancelRequest) Descriptor() ([]byte, []int) {
	return file_reminder_proto_rawDescGZIP(), []int{2}
}

func (x *CancelRequest) GetBookingId() string {
	if x != nil {
		return x.BookingId
	}
	return ""
}

type CancelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"` // CANCELLED | MISSING
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelResponse) Reset() {
	*x = CancelResponse{}
	mi := &file_reminder_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelResponse) ProtoMessage() {}

func (x *CancelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reminder_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelResponse.ProtoReflect.Descriptor instead.
func (*CancelResponse) Descriptor() ([]byte, []int) {
	return file_reminder_proto_rawDescGZIP(), []int{3}
}

func (x *CancelResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_reminder_proto protoreflect.FileDescriptor

const file_reminder_proto_rawDesc = "" +
	"\n" +
	"\x0ereminder.proto\x12\x11cine.reminders.v1\"\xe4\x01\n" +
	"\x0fScheduleRequest\x12\x1d\n" +
	"\n" +
	"booking_id\x18\x01 \x01(\tR\tbookingId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x19\n" +
	"\bmovie_id\x18\x04 \x01(\tR\amovieId\x12\x1f\n" +
	"\vmovie_title\x18\x05 \x01(\tR\n" +
	"movieTitle\x12\x12\n" +
	"\x04hall\x18\x06 \x01(\tR\x04hall\x12\x1d\n" +
	"\n" +
	"session_at\x18\a \x01(\tR\tsessionAt\x12\x14\n" +
	"\x05seats\x18\b \x03(\tR\x05seats\"A\n" +
	"\x10ScheduleResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x15\n" +
	"\x06due_at\x18\x02 \x01(\tR\x05dueAt\".\n" +
	"\rCancelRequest\x12\x1d\n" +
	"\n" +
	"booking_id\x18\x01 \x01(\tR\tbookingId\"(\n" +
	"\x0eCancelResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status2\xaf\x01\n" +
	"\tReminders\x12S\n" +
	"\bSchedule\x12\".cine.reminders.v1.ScheduleRequest\x1a#.cine.reminders.v1.ScheduleResponse\x12M\n" +
	"\x06Cancel\x12 .cine.reminders.v1.CancelRequest\x1a!.cine.reminders.v1.CancelResponseB%Z#reminder-service/internal/pb;cinepbb\x06proto3"

var (
	file_reminder_proto_rawDescOnce sync.Once
	file_reminder_proto_rawDescData []byte
)

func file_reminder_proto_rawDescGZIP() []byte {
	file_reminder_proto_rawDescOnce.Do(func() {
		file_reminder_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_reminder_proto_rawDesc), len(file_reminder_proto_rawDesc)))
	})
	return file_reminder_proto_rawDescData
}

var file_reminder_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_reminder_proto_goTypes = []any{
	(*ScheduleRequest)(nil),  // 0: cine.reminders.v1.ScheduleRequest
	(*ScheduleResponse)(nil), // 1: cine.reminders.v1.ScheduleResponse
	(*CancelRequest)(nil),    // 2: cine.reminders.v1.CancelRequest
	(*CancelResponse)(nil),   // 3: cine.reminders.v1.CancelResponse
}
var file_reminder_proto_depIdxs = []int32{
	0, // 0: cine.reminders.v1.Reminders.Schedule:input_type -> cine.reminders.v1.ScheduleRequest
	2, // 1: cine.reminders.v1.Reminders.Cancel:input_type -> cine.reminders.v1.CancelRequest
	1, // 2: cine.reminders.v1.Reminders.Schedule:output_type -> cine.reminders.v1.ScheduleResponse
	3, // 3: cine.reminders.v1.Reminders.Cancel:output_type -> cine.reminders.v1.CancelResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_reminder_proto_init() }
func file_reminder_proto_init() {
	if File_reminder_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_reminder_proto_rawDesc), len(file_reminder_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_reminder_proto_goTypes,
		DependencyIndexes: file_reminder_proto_depIdxs,
		MessageInfos:      file_reminder_proto_msgTypes,
	}.Build()
	File_reminder_proto = out.File
	file_reminder_proto_goTypes = nil
	file_reminder_proto_depIdxs = nil
}
