// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: reminder.proto

// Reminder — gRPC-контракт сервиса напоминаний о сеансах.
// Общий контракт API (NestJS) и reminder-service (Go): proto-loader
// на стороне Node читает этот файл в рантайме, Go-сторона использует
// сгенерированный код (scripts/protogen.sh -> internal/pb).

package cinepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Reminders_Schedule_FullMethodName = "/cine.reminders.v1.Reminders/Schedule"
	Reminders_Cancel_FullMethodName   = "/cine.reminders.v1.Reminders/Cancel"
)

// RemindersClient is the client API for Reminders service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Сервис напоминаний: API планирует письмо при подтверждении брони
// и гасит при возврате билетов. Момент наступает внутри сервиса
// (тикер), доставка — событием user.session.reminder в RabbitMQ.
type RemindersClient interface {
	// Запланировать напоминание на сеанс (идемпотентно по bookingId).
	Schedule(ctx context.Context, in *ScheduleRequest, opts ...grpc.CallOption) (*ScheduleResponse, error)
	// Погасить напоминание брони (возврат билетов). Отсутствующее — не ошибка.
	Cancel(ctx context.Context, in *CancelRequest, opts ...grpc.CallOption) (*CancelResponse, error)
}

type remindersClient struct {
	cc grpc.ClientConnInterface
}

func NewRemindersClient(cc grpc.ClientConnInterface) RemindersClient {
	return &remindersClient{cc}
}

func (c *remindersClient) Schedule(ctx context.Context, in *ScheduleRequest, opts ...grpc.CallOption) (*ScheduleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScheduleResponse)
	err := c.cc.Invoke(ctx, Reminders_Schedule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *remindersClient) Cancel(ctx context.Context, in *CancelRequest, opts ...grpc.CallOption) (*CancelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelResponse)
	err := c.cc.Invoke(ctx, Reminders_Cancel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RemindersServer is the server API for Reminders service.
// All implementations must embed UnimplementedRemindersServer
// for forward compatibility.
//
// Сервис напоминаний: API планирует письмо при подтверждении брони
// и гасит при возврате билетов. Момент наступает внутри сервиса
// (тикер), доставка — событием user.session.reminder в RabbitMQ.
type RemindersServer interface {
	// Запланировать напоминание на сеанс (идемпотентно по bookingId).
	Schedule(context.Context, *ScheduleRequest) (*ScheduleResponse, error)
	// Погасить напоминание брони (возврат билетов). Отсутствующее — не ошибка.
	Cancel(context.Context, *CancelRequest) (*CancelResponse, error)
	mustEmbedUnimplementedRemindersServer()
}

// UnimplementedRemindersServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRemindersServer struct{}

func (UnimplementedRemindersServer) Schedule(context.Context, *ScheduleRequest) (*ScheduleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Schedule not implemented")
}
func (UnimplementedRemindersServer) Cancel(context.Context, *CancelRequest) (*CancelResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Cancel not implemented")
}
func (UnimplementedRemindersServer) mustEmbedUnimplementedRemindersServer() {}
func (UnimplementedRemindersServer) testEmbeddedByValue()                   {}

// UnsafeRemindersServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RemindersServer will
// result in compilation errors.
type UnsafeRemindersServer interface {
	mustEmbedUnimplementedRemindersServer()
}

func RegisterRemindersServer(s grpc.ServiceRegistrar, srv RemindersServer) {
	// If the following call panics, it indicates UnimplementedRemindersServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Reminders_ServiceDesc, srv)
}

func _Reminders_Schedule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScheduleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RemindersServer).Schedule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Reminders_Schedule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RemindersServer).Schedule(ctx, req.(*ScheduleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Reminders_Cancel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RemindersServer).Cancel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Reminders_Cancel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RemindersServer).Cancel(ctx, req.(*CancelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Reminders_ServiceDesc is the grpc.ServiceDesc for Reminders service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Reminders_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cine.reminders.v1.Reminders",
	HandlerType: (*RemindersServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Schedule",
			Handler:    _Reminders_Schedule_Handler,
		},
		{
			MethodName: "Cancel",
			Handler:    _Reminders_Cancel_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "reminder.proto",
}
