// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: ratelimiter.proto

// RateLimiter — gRPC-контракт «Привратника»: сервиса лимитов частоты.
// Общий контракт API (NestJS) и ratelimiter-service (Go): proto-loader
// на стороне Node читает этот файл в рантайме, Go-сторона использует
// сгенерированный код (scripts/protogen.sh -> internal/pb).
// Политики (ёмкость/долив по действию) живут в самом сервисе —
// вызывающий присылает только действие и ключ клиента.

package cinepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RateLimiter_Check_FullMethodName = "/cine.ratelimiter.v1.RateLimiter/Check"
)

// RateLimiterClient is the client API for RateLimiter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Сервис лимитов: гварды API спрашивают один токен token-корзины
// до допуска действия (создание брони, вход). Отказ — не ошибка RPC:
// allowed=false + retry_after_ms, чтобы вызывающий мог погасить
// падение сервиса fallback'ом (fail-open на стороне API).
type RateLimiterClient interface {
	Check(ctx context.Context, in *CheckRateRequest, opts ...grpc.CallOption) (*CheckRateResponse, error)
}

type rateLimiterClient struct {
	cc grpc.ClientConnInterface
}

func NewRateLimiterClient(cc grpc.ClientConnInterface) RateLimiterClient {
	return &rateLimiterClient{cc}
}

func (c *rateLimiterClient) Check(ctx context.Context, in *CheckRateRequest, opts ...grpc.CallOption) (*CheckRateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckRateResponse)
	err := c.cc.Invoke(ctx, RateLimiter_Check_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RateLimiterServer is the server API for RateLimiter service.
// All implementations must embed UnimplementedRateLimiterServer
// for forward compatibility.
//
// Сервис лимитов: гварды API спрашивают один токен token-корзины
// до допуска действия (создание брони, вход). Отказ — не ошибка RPC:
// allowed=false + retry_after_ms, чтобы вызывающий мог погасить
// падение сервиса fallback'ом (fail-open на стороне API).
type RateLimiterServer interface {
	Check(context.Context, *CheckRateRequest) (*CheckRateResponse, error)
	mustEmbedUnimplementedRateLimiterServer()
}

// UnimplementedRateLimiterServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRateLimiterServer struct{}

func (UnimplementedRateLimiterServer) Check(context.Context, *CheckRateRequest) (*CheckRateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Check not implemented")
}
func (UnimplementedRateLimiterServer) mustEmbedUnimplementedRateLimiterServer() {}
func (UnimplementedRateLimiterServer) testEmbeddedByValue()                     {}

// UnsafeRateLimiterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RateLimiterServer will
// result in compilation errors.
type UnsafeRateLimiterServer interface {
	mustEmbedUnimplementedRateLimiterServer()
}

func RegisterRateLimiterServer(s grpc.ServiceRegistrar, srv RateLimiterServer) {
	// If the following call panics, it indicates UnimplementedRateLimiterServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RateLimiter_ServiceDesc, srv)
}

func _RateLimiter_Check_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckRateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RateLimiterServer).Check(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RateLimiter_Check_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RateLimiterServer).Check(ctx, req.(*CheckRateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RateLimiter_ServiceDesc is the grpc.ServiceDesc for RateLimiter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RateLimiter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cine.ratelimiter.v1.RateLimiter",
	HandlerType: (*RateLimiterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Check",
			Handler:    _RateLimiter_Check_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ratelimiter.proto",
}
