// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: ratelimiter.proto

// RateLimiter — gRPC-контракт «Привратника»: сервиса лимитов частоты.
// Общий контракт API (NestJS) и ratelimiter-service (Go): proto-loader
// на стороне Node читает этот файл в рантайме, Go-сторона использует
// сгенерированный код (scripts/protogen.sh -> internal/pb).
// Политики (ёмкость/долив по действию) живут в самом сервисе —
// вызывающий присылает только действие и ключ клиента.

package cinepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CheckRateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        string                 `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"` // bookings.create | auth.login
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`       // кто спрашивает: user id / email / ip
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckRateRequest) Reset() {
	*x = CheckRateRequest{}
	mi := &file_ratelimiter_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckRateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckRateRequest) ProtoMessage() {}

func (x *CheckRateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ratelimiter_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckRateRequest.ProtoReflect.Descriptor instead.
func (*CheckRateRequest) Descriptor() ([]byte, []int) {
	return file_ratelimiter_proto_rawDescGZIP(), []int{0}
}

func (x *CheckRateRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *CheckRateRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type CheckRateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Allowed       bool                   `protobuf:"varint,1,opt,name=allowed,proto3" json:"allowed,omitempty"`                                 // снят ли токен
	RetryAfterMs  int32                  `protobuf:"varint,2,opt,name=retry_after_ms,json=retryAfterMs,proto3" json:"retry_after_ms,omitempty"` // сколько ждать при allowed=false
	Remaining     int32                  `protobuf:"varint,3,opt,name=remaining,proto3" json:"remaining,omitempty"`                             // целых токенов после решения
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`                                     // предел в минуту (политика сервиса)
	Capacity      int32                  `protobuf:"varint,5,opt,name=capacity,proto3" json:"capacity,omitempty"`                               // burst-ёмкость корзины
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckRateResponse) Reset() {
	*x = CheckRateResponse{}
	mi := &file_ratelimiter_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckRateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckRateResponse) ProtoMessage() {}

func (x *CheckRateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ratelimiter_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckRateResponse.ProtoReflect.Descriptor instead.
func (*CheckRateResponse) Descriptor() ([]byte, []int) {
	return file_ratelimiter_proto_rawDescGZIP(), []int{1}
}

func (x *CheckRateResponse) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

func (x *CheckRateResponse) GetRetryAfterMs() int32 {
	if x != nil {
		return x.RetryAfterMs
	}
	return 0
}

func (x *CheckRateResponse) GetRemaining() int32 {
	if x != nil {
		return x.Remaining
	}
	return 0
}

func (x *CheckRateResponse) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *CheckRateResponse) GetCapacity() int32 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

var File_ratelimiter_proto protoreflect.FileDescriptor

const file_ratelimiter_proto_rawDesc = "" +
	"\n" +
	"\x11ratelimiter.proto\x12\x13cine.ratelimiter.v1\"<\n" +
	"\x10CheckRateRequest\x12\x16\n" +
	"\x06action\x18\x01 \x01(\tR\x06action\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\"\xa3\x01\n" +
	"\x11CheckRateResponse\x12\x18\n" +
	"\aallowed\x18\x01 \x01(\bR\aallowed\x12$\n" +
	"\x0eretry_after_ms\x18\x02 \x01(\x05R\fretryAfterMs\x12\x1c\n" +
	"\tremaining\x18\x03 \x01(\x05R\tremaining\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\x12\x1a\n" +
	"\bcapacity\x18\x05 \x01(\x05R\bcapacity2e\n" +
	"\vRateLimiter\x12V\n" +
	"\x05Check\x12%.cine.ratelimiter.v1.CheckRateRequest\x1a&.cine.ratelimiter.v1.CheckRateResponseB(Z&ratelimiter-service/internal/pb;cinepbb\x06proto3"

var (
	file_ratelimiter_proto_rawDescOnce sync.Once
	file_ratelimiter_proto_rawDescData []byte
)

func file_ratelimiter_proto_rawDescGZIP() []byte {
	file_ratelimiter_proto_rawDescOnce.Do(func() {
		file_ratelimiter_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ratelimiter_proto_rawDesc), len(file_ratelimiter_proto_rawDesc)))
	})
	return file_ratelimiter_proto_rawDescData
}

var file_ratelimiter_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_ratelimiter_proto_goTypes = []any{
	(*CheckRateRequest)(nil),  // 0: cine.ratelimiter.v1.CheckRateRequest
	(*CheckRateResponse)(nil), // 1: cine.ratelimiter.v1.CheckRateResponse
}
var file_ratelimiter_proto_depIdxs = []int32{
	0, // 0: cine.ratelimiter.v1.RateLimiter.Check:input_type -> cine.ratelimiter.v1.CheckRateRequest
	1, // 1: cine.ratelimiter.v1.RateLimiter.Check:output_type -> cine.ratelimiter.v1.CheckRateResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ratelimiter_proto_init() }
func file_ratelimiter_proto_init() {
	if File_ratelimiter_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ratelimiter_proto_rawDesc), len(file_ratelimiter_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ratelimiter_proto_goTypes,
		DependencyIndexes: file_ratelimiter_proto_depIdxs,
		MessageInfos:      file_ratelimiter_proto_msgTypes,
	}.Build()
	File_ratelimiter_proto = out.File
	file_ratelimiter_proto_goTypes = nil
	file_ratelimiter_proto_depIdxs = nil
}
